# make it explicit that we favor the new container-based travis workers
dist: trusty
sudo: false

language: python

# Pre-install packages for the ubuntu distribution
cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
addons:
  apt:
    packages:
      - python-numpy
      - python-scipy
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir
    - MODULE=sksports
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4

matrix:
  include:
    # Latest release
    - env: DISTRIB="conda" PYTHON_VERSION="2.7"
    - env: DISTRIB="conda" PYTHON_VERSION="3.5"
    - env: DISTRIB="conda" PYTHON_VERSION="3.6"

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f53515270da68e1b5ec6
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
